- name: Disallow root SSH access.
  ansible.builtin.lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^PermitRootLogin"
    line: "PermitRootLogin no"
    state: present
  notify: restart ssh

- name: Set SSH port.
  ansible.builtin.lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^Port"
    line: "Port {{ server_ssh_port }}"
    state: present
  notify: restart ssh

- name: Disallow password authentication over SSH.
  ansible.builtin.lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^PasswordAuthentication"
    line: "PasswordAuthentication no"
    state: present
  notify: restart ssh

- name: Open the firewall port for SSH.
  command: "ufw allow {{ server_ssh_port }}/tcp"
  become: true
  register: ufw_allow_ssh_output
  changed_when: ufw_allow_ssh_output.stdout is search('Rules updated')
    
- name: Get the UFW status.
  command: "ufw status"
  become: true
  register: ufw_status_output
  changed_when: false

- name: Ensure UFW is enabled.
  command: "ufw enable"
  become: true
  when: '"Status: active" not in ufw_status_output.stdout'