---
- name: Set users variable when there are NOT any additional users.
  ansible.builtin.set_fact:
    flattend_users: "{{ users }}"
  when: additional_users is not defined

- name: Set users variable when there ARE additional users.
  ansible.builtin.set_fact:
    flattend_users: "{{ users + additional_users }}"
  when: additional_users is defined

- name: Configure users.
  ansible.builtin.user:
    name: '{{ item.username }}'
    groups: '{{ item.groups | join(",") | default(omit) }}'
    shell: '{{ item.shell | default(omit) }}'
    password: '{{ item.password | default(omit) }}'
    comment: '{{ item.name | default(omit) }}'
    uid: '{{ item.uid | default(omit) }}'
    home: '{{ item.homedir | default(omit) }}'
    state: '{{ item.state | default("present") }}'
  with_items: "{{ users }}"
  register: created_users

- name: Configure authorized keys.
  ansible.posix.authorized_key:
    user: '{{item.0.username}}'
    key: '{{item.1.public_key}}'
    state: '{{item.1.state | default ("present")}}'
  with_subelements:
    - "{{ users }}"
    - authorized_keys
    - skip_missing: true
  when: item.0.state | default("present") != 'absent'