---
- name: Verify
  hosts: all
  gather_facts: false
  vars_files:
    - vars.yml
  tasks:   
    - name: Check current timezone
      command: timedatectl show --property=Timezone --value
      register: current_timezone
      changed_when: false

    - name: Assert timezone is correct
      assert:
        that:
          - current_timezone.stdout == server_timezone
        fail_msg: "Timezone is not set correctly"
      
    - name: Check to see if the user "bob" exists.
      command: whoami
      become_user: bob
      register: bob_whoami
      changed_when: false

    - name: Assert Bob user exists.
      assert:
        that:
          - current_timezone.stdout == server_timezone
        fail_msg: "Failed to assert the user 'bob' exists."