---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  gather_facts: false
  vars_files:
    - vars.yml
  tasks:   
    - name: Check current timezone
      command: timedatectl show --property=Timezone --value
      register: current_timezone
      changed_when: false

    - name: Assert timezone is correct
      assert:
        that:
          - current_timezone.stdout == server_timezone
        fail_msg: "Timezone is not set correctly"
