---
- name: Verify
  hosts: all
  gather_facts: false
  vars_files:
    - vars.yml
  tasks:   
    - name: Check current timezone
      command: timedatectl show --property=Timezone --value
      register: current_timezone
      changed_when: false

    - name: Assert timezone is correct
      assert:
        that:
          - current_timezone.stdout == server_timezone
        fail_msg: "Timezone is not set correctly"
      
    - name: Get Charlie user info.
      ansible.builtin.user:
        name: charlie
      register: charlie_user_test

    - name: Assert charlie user exists.
      assert:
        that:
          - charlie_user_test.name == 'charlie'
          - charlie_user_test.changed == false
        fail_msg: "Failed to assert the user 'charlie' exists."